name: My First Surge Assignment

on:
  push:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install NodeJS
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12
        run: npm install -g surge
    - name: Run Surge
      run: surge ./bootcamp2020Assignment1.surge.sh --token ${{secrets.SURGE_TOKEN}}
      
